version: "2.4"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    volumes:
      - /mnt/e/homeflix/config/plex:/config
      - /mnt/e/Warez:/warez/e
      - /mnt/f/Warez:/warez/f
      - /mnt/g/Warez:/warez/g
    ports:
      - 1900:1900
      - 3005:3005
      - 5353:5353
      - 8324:8324
      - 32400:32400
      - 32410:32410
      - 32412-32414:32412-32414
      - 32469:32469
    expose:
      - 32400
    environment:
      # - PLEX_CLAIM=claim-xxx # See https://www.plex.tv/claim/
      - VERSION=docker
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu

  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - HAS_IPV6=false
    volumes:
      - /mnt/e/homeflix/config/sabnzbd:/config
      - /mnt/e/Warez/Usenet:/downloads
    ports:
      - 8081:8080
    depends_on:
      - wireguard
    network_mode: service:wireguard
    expose:
      - 8080
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /mnt/e/homeflix/config/sonarr:/config
      - /mnt/e/Warez:/warez/e
      - /mnt/f/Warez:/warez/f
      - /mnt/g/Warez:/warez/g
      - /mnt/e/Warez/Usenet:/downloads
    expose:
      - 8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /mnt/e/homeflix/config/radarr:/config
      - /mnt/e/Warez:/warez/e
      - /mnt/g/Warez:/warez/g
      - /mnt/e/Warez/Usenet:/downloads
    expose:
      - 7878
    restart: unless-stopped

  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /mnt/e/homeflix/config/tautulli:/config
    ports:
      - 8181:8181
    expose:
      - 8181
    restart: unless-stopped

  nzbhydra2:
    image: linuxserver/nzbhydra2
    container_name: nzbhydra2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /mnt/e/homeflix/config/nzbhydra2:/config
      - /mnt/e/Warez/Usenet/nzb:/downloads
    ports:
      - 5076:5076
    expose:
      - 5076
    restart: unless-stopped

  caddy:
    build: caddy
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - docker-compose.env
    restart: unless-stopped

  app:
    build: app
    container_name: app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-compose.yml:/docker-compose.yml
    expose:
      - 3000
    restart: unless-stopped

  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - ./wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820
    restart: unless-stopped

  test-wireguard:
    image: alpine
    depends_on:
      - wireguard
    network_mode: service:wireguard
    command: sh -c 'sleep 1; wget -q -O - https://ifconfig.me/ip; echo'

volumes:
  caddy_data:
    external: true
  caddy_config:
  app_error:
